import { NextRequest, NextResponse } from "next/server";
import fs from "fs/promises";
import fsSync from "fs";
import path from "path";

import {
  buildRetrievalPackage,
} from "../../../../../../07_AUTOMATION/knowledge-retrieval/retriever";

import {
  detectWriterOutputContract,
  buildWriterSystemPrompt,
  buildWriterUserPrompt,
} from "../../../../../../07_AUTOMATION/writer";

import {
  buildPlannerSystemPrompt,
  buildPlannerUserPrompt,
  parseContentPlan,
  formatContentPlanForWriter,
  CONTENT_PLAN_SCHEMA,
} from "../../../../../../07_AUTOMATION/content-planner";



import {
  validateWriterOutput,
} from "../../../../../../07_AUTOMATION/validator";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/*
 * ==================================================
 * PROJECT ROOT DETECTION (MONOREPO & VERCEL SAFE)
 * ==================================================
 */

function resolveProjectRoot(): string {
  const cwd = process.cwd();

  const twoUp = path.resolve(cwd, "../..");

  if (
    fsSync.existsSync(
      path.join(twoUp, "00_SYSTEM")
    )
  ) {
    return twoUp;
  }

  const oneUp = path.resolve(cwd, "..");

  if (
    fsSync.existsSync(
      path.join(oneUp, "00_SYSTEM")
    )
  ) {
    return oneUp;
  }

  return cwd;
}

const PROJECT_ROOT =
  resolveProjectRoot();

/*
 * ==================================================
 * CONTENT STRATEGY CONTEXT
 * ==================================================
 *
 * These documents are the strategic layer for Planner.
 * They are not generated by Retriever.
 */

const STRATEGY_FILES = [
  "04_CONTENT/CONTENT_CHANNEL_ARCHITECTURE.md",
  "04_CONTENT/CONTENT_STRATEGY.md",
  "04_CONTENT/CHANNEL_STRATEGY.md",
];

async function loadStrategyContext(): Promise<string> {
  const blocks: string[] = [];

  for (
    const relativePath
    of STRATEGY_FILES
  ) {
    const absolutePath =
      path.join(
        PROJECT_ROOT,
        relativePath
      );

    try {
      const content =
        await fs.readFile(
          absolutePath,
          "utf8"
        );

      blocks.push(`
==================================================
STRATEGIC DOCUMENT: ${relativePath}
==================================================

${content}

==================================================
END STRATEGIC DOCUMENT: ${relativePath}
==================================================
`);
    } catch (error) {
      console.warn(
        `STRATEGY DOCUMENT NOT LOADED: ${relativePath}`,
        error
      );
    }
  }

  if (!blocks.length) {
    return `
NO CONTENT STRATEGY DOCUMENTS WERE LOADED.

Planner must rely on the available project context
and must not invent strategic rules.
`;
  }

  return blocks.join("\n");
}

/*
 * ==================================================
 * RETRIEVAL LIMITS
 * ==================================================
 */

const RETRIEVAL_MAX_CHARACTERS =
  180_000;

const RETRIEVAL_MAX_SOURCES =
  30;

/*
 * ==================================================
 * TYPES
 * ==================================================
 */

type ContextProfile =
  | "CONTENT"
  | "RESEARCH"
  | "ANALYTICS"
  | "GENERAL";

type AIRequest = {
  task?: string;
  mode?: string;
  profile?: ContextProfile;
  paths?: string[];
  includeRadar?: boolean;
  channel?: string;
};

type RetrievalItem = {
  path?: string;
  type?: string;
  title?: string;
  purpose?: string;
  fileName?: string;
  sourceRole?: string;
  keywords?: string[];
  radarMetadata?:
    Record<string, unknown> | null;
};

type RetrievalCandidate = {
  item: RetrievalItem;
  role?: string;
  size?: number;
  relevance?: number;
  reasons?: string[];
};

type RetrievalPackage = {
  generatedAt: string;

  limits: {
    maxCharacters: number;
    maxSources: number;
  };

  composition:
    Record<string, number>;

  selected:
    RetrievalCandidate[];
};

/*
 * ==================================================
 * PATH SAFETY
 * ==================================================
 */

function safeProjectPath(
  relativePath: string
): string | null {
  const normalized =
    relativePath
      .replace(/\\/g, "/")
      .replace(/^\/+/, "");

  /*
   * Radar virtual references are never
   * directly materialized as files.
   */
  if (
    normalized.includes(
      "#signal-"
    )
  ) {
    return null;
  }

  const absolute =
    path.resolve(
      PROJECT_ROOT,
      normalized
    );

  if (
    absolute !== PROJECT_ROOT &&
    !absolute.startsWith(
      PROJECT_ROOT + path.sep
    )
  ) {
    return null;
  }

  return absolute;
}

/*
 * ==================================================
 * RETRIEVAL SEED
 * ==================================================
 *
 * Deterministic retrieval seed.
 * Planner runs AFTER retrieval.
 */

function buildRetrievalSeed(
  task: string,
  profile: ContextProfile,
  requestedPaths: string[]
) {
  const defaultPriorities: Record<
    ContextProfile,
    string[]
  > = {
    CONTENT: [
      "01_KNOWLEDGE",
      "03_AUDIENCE",
      "02_RESEARCH",
      "04_CONTENT",
      "05_SEO",
      "08_INPUT",
    ],

    RESEARCH: [
      "02_RESEARCH",
      "01_KNOWLEDGE",
      "03_AUDIENCE",
      "04_CONTENT",
      "05_SEO",
      "08_INPUT",
    ],

    ANALYTICS: [
      "06_ANALYTICS",
      "02_RESEARCH",
      "03_AUDIENCE",
      "01_KNOWLEDGE",
      "04_CONTENT",
      "05_SEO",
      "08_INPUT",
    ],

    GENERAL: [
      "01_KNOWLEDGE",
      "02_RESEARCH",
      "03_AUDIENCE",
      "04_CONTENT",
      "05_SEO",
      "06_ANALYTICS",
      "08_INPUT",
    ],
  };

  return {
    audience: "",

    topic:
      task,

    subtopic:
      profile,

    goal:
      task,

    audienceNeed: "",

    keyMessage:
      task,

    contentAngle:
      task,

    researchSignals: [],

    knowledgeNeeds: [
      "реальный опыт",
      "экспертные знания",
      "актуальные исследования",
      "аудитория",
    ],

    radarSignals: [
      task,
    ],

    seoConsiderations: [],

    constraints: [
      "Не придумывать факты, которых нет в библиотеке проекта.",
    ],

    sourcePriorities: [
      ...requestedPaths,
      ...defaultPriorities[
        profile
      ],
    ],
  };
}

/*
 * ==================================================
 * RETRIEVAL CONTEXT RESOLUTION
 * ==================================================
 */

async function readSelectedItemContent(
  candidate: RetrievalCandidate
): Promise<string> {
  const item =
    candidate.item;

  if (!item) {
    return "";
  }

  /*
   * Radar virtual source.
   */
  if (
    item.type ===
    "radar_signal"
  ) {
    const metadata =
      item.radarMetadata
        ? `\nRADAR METADATA:\n${JSON.stringify(
            item.radarMetadata,
            null,
            2
          )}`
        : "";

    return [
      item.title,
      item.purpose,
      ...(item.keywords ||
        []),
      metadata,
    ]
      .filter(Boolean)
      .join("\n");
  }

  const relativePath =
    String(
      item.path || ""
    );

  const absolutePath =
    safeProjectPath(
      relativePath
    );

  if (!absolutePath) {
    return [
      item.title,
      item.purpose,
      ...(item.keywords ||
        []),
    ]
      .filter(Boolean)
      .join("\n");
  }

  try {
    const stat =
      await fs.stat(
        absolutePath
      );

    if (
      !stat.isFile()
    ) {
      return [
        item.title,
        item.purpose,
      ]
        .filter(Boolean)
        .join("\n");
    }

    if (
      stat.size >
      1_500_000
    ) {
      return [
        item.title,
        item.purpose,
      ]
        .filter(Boolean)
        .join("\n");
    }

    return await fs.readFile(
      absolutePath,
      "utf8"
    );
  } catch {
    return [
      item.title,
      item.purpose,
      ...(item.keywords ||
        []),
    ]
      .filter(Boolean)
      .join("\n");
  }
}

async function buildRetrievedContext(
  retrievalPackage: RetrievalPackage,
  includeRadar: boolean
): Promise<{
  filesLoaded: number;
  contextCharacters: number;
  sources: string[];
  context: string;
}> {
  const selected =
    includeRadar
      ? retrievalPackage.selected
      : retrievalPackage.selected.filter(
          candidate =>
            candidate.item?.type !==
            "radar_signal"
        );

  const blocks: string[] =
    [];

  const sources: string[] =
    [];

  let totalCharacters =
    0;

  for (
    const candidate
    of selected
  ) {
    const item =
      candidate.item;

    if (!item) {
      continue;
    }

    if (
      !includeRadar &&
      item.type ===
        "radar_signal"
    ) {
      continue;
    }

    const content =
      await readSelectedItemContent(
        candidate
      );

    if (
      !content.trim()
    ) {
      continue;
    }

    const pathLabel =
      String(
        item.path ||
          item.title ||
          "unknown-source"
      );

    const role =
      String(
        candidate.role ||
          item.sourceRole ||
          item.type ||
          "source"
      );

    const block = `
==================================================
SOURCE: ${pathLabel}
ROLE: ${role}
==================================================

${content}

==================================================
END SOURCE: ${pathLabel}
==================================================
`;

    const nextCharacters =
      totalCharacters +
      block.length;

    if (
      nextCharacters >
      RETRIEVAL_MAX_CHARACTERS
    ) {
      continue;
    }

    blocks.push(
      block
    );

    sources.push(
      pathLabel
    );

    totalCharacters =
      nextCharacters;
  }

  return {
    filesLoaded:
      sources.length,

    contextCharacters:
      totalCharacters,

    sources,

    context:
      blocks.length
        ? blocks.join(
            "\n"
          )
        : `
NO RETRIEVED PROJECT DOCUMENTS WERE LOADED.

Do not invent project-specific information.
State that the required context is missing.
`,
  };
}

/*
 * ==================================================
 * SYSTEM PROMPT
 * ==================================================
 */

function buildSystemPrompt(
  profile: ContextProfile
): string {
  return `
You are the AI execution layer of DanceContentEngine_v1.

You are an executor working inside an existing project methodology.

CONTEXT PROFILE:
${profile}

Read the supplied retrieved project context before acting.

CORE PRINCIPLES:

1. Respect the existing project architecture.
2. Do not invent facts, prices, schedules, events, achievements or business results.
3. Distinguish FACT, INFERENCE, HYPOTHESIS and RECOMMENDATION when relevant.
4. Preserve source information.
5. Treat 01_KNOWLEDGE as expert knowledge and owner experience.
6. Treat 02_RESEARCH as research evidence.
7. Treat 02_RESEARCH/Аналитик as research produced by the AI Analyst.
8. Treat 03_AUDIENCE as audience information.
9. Treat 04_CONTENT as content methodology and rules.
10. Treat 05_SEO as SEO methodology and search rules.
11. Treat 06_ANALYTICS as measurement information.
12. Treat RADAR data as external signals, not automatically verified truth.
13. If information is missing, say so.
14. Do not silently rewrite the methodology.
15. Do not create new architecture unless explicitly requested.
16. Use multiple relevant sources when creating content.
17. Avoid repetitive, generic and template-like content.
18. When creating content, combine different relevant types of project material.
19. Recommendations must be based on available evidence.
20. Never claim that an action has happened unless the supplied context confirms it.
21. The retrieved context is a bounded selection from the full project library; do not assume it is the whole library.

PROFILE BEHAVIOR:

CONTENT
- Prefer a broad mixture of CONTENT, AUDIENCE, RESEARCH, KNOWLEDGE and SEO material.
- Use RADAR as a source of current external signals when available.
- Do not build content from a single document.
- Seek interesting combinations of different evidence and ideas.
- Use owner knowledge when relevant.
- Avoid formulaic repetition.

RESEARCH
- Prefer RESEARCH and KNOWLEDGE.
- Use AUDIENCE and RADAR when relevant.
- Focus on evidence, findings, gaps and contradictions.

ANALYTICS
- Prefer ANALYTICS.
- Use RESEARCH, AUDIENCE and KNOWLEDGE when useful.
- Focus on measurements, patterns, anomalies and conclusions supported by data.

GENERAL
- Use the broad retrieved project context.
- Select the most relevant available information for the task.

GENERAL DATA FLOW:

INPUT
→ Librarian
→ Retriever
→ Content Plan
→ Draft
→ Validation
→ Approved
→ Published
→ Analytics
→ feedback into Research / Audience / Knowledge

ROLES:

LIBRARIAN
Maintains the factual map of the information library.

RETRIEVER
Builds a bounded and diverse context package from that map.

ANALYST
Researches and structures evidence.

RADAR
Collects external signals.

EDITOR
Structures knowledge and controls quality.

WRITER
Creates content.

SEO ENGINE
Works with search demand.

ANALYTICS
Measures results.

The LLM executes these roles according to the task.
It does not own the system.

When creating content, prefer useful, specific, varied and evidence-based material over generic templates.
`;
}

/*
 * ==================================================
 * CONTEXT FORMATTER
 * ==================================================
 */

function formatContext(
  context: string
): string {
  return context;
}

/*
 * ==================================================
 * GEMINI
 * ==================================================
 */

const GEMINI_API_KEY =
  process.env.GEMINI_API_KEY ||
  "";

async function callAI(
  systemPrompt: string,
  userPrompt: string,
  maxOutputTokens = 2000,
  options: {
    responseMimeType?: string;
    responseSchema?: unknown;
  } = {}
) {
  if (
    !GEMINI_API_KEY
  ) {
    throw new Error(
      "GEMINI_API_KEY is not configured in environment variables."
    );
  }

  const controller =
    new AbortController();

  const timeoutId =
    setTimeout(
      () =>
        controller.abort(),
      60000
    );

  try {
    const url =
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${GEMINI_API_KEY}`;

    const response =
      await fetch(
        url,
        {
          method:
            "POST",

          signal:
            controller.signal,

          headers: {
            "Content-Type":
              "application/json",
          },

          body:
            JSON.stringify({
              systemInstruction: {
                parts: [
                  {
                    text:
                      systemPrompt,
                  },
                ],
              },

              contents: [
                {
                  role:
                    "user",

                  parts: [
                    {
                      text:
                        userPrompt,
                    },
                  ],
                },
              ],

              generationConfig: {
                temperature:
                  0.7,

                maxOutputTokens,

                ...(options.responseMimeType
                  ? {
                      responseMimeType:
                        options.responseMimeType,
                    }
                  : {}),

                ...(options.responseSchema
                  ? {
                      responseSchema:
                        options.responseSchema,
                    }
                  : {}),
              },
            }),
        }
      );

    const raw =
      await response.text();

    if (
      !response.ok
    ) {
      throw new Error(
        `Gemini API error ${response.status}: ${raw.slice(
          0,
          1000
        )}`
      );
    }

    let data: any;

    try {
      data =
        JSON.parse(
          raw
        );
    } catch {
      throw new Error(
        "Gemini API returned invalid JSON."
      );
    }

    const content =
      data?.candidates?.[0]
        ?.content?.parts?.[0]
        ?.text;

    if (
      typeof content !==
        "string" ||
      !content.trim()
    ) {
      throw new Error(
        "Gemini API returned no message content."
      );
    }

    return {
      content,

      model:
        "gemini-2.5-flash",

      usage:
        data?.usageMetadata ||
        null,

      finishReason:
        data?.candidates?.[0]
          ?.finishReason ||
        null,
    };
  } finally {
    clearTimeout(
      timeoutId
    );
  }
}

/*
 * ==================================================
 * GET
 * ==================================================
 */

export async function GET() {
  if (
    !GEMINI_API_KEY
  ) {
    return NextResponse.json({
      ok: false,
      error:
        "GEMINI_API_KEY is missing",
    });
  }

  try {
    const res =
      await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models?key=${GEMINI_API_KEY}`
      );

    const data =
      await res.json();

    const availableModels =
      data?.models
        ? data.models.map(
            (m: any) =>
              m.name.replace(
                "models/",
                ""
              )
          )
        : [];

    return NextResponse.json({
      ok: true,

      service:
        "DanceContentEngine AI Gateway",

      provider:
        "Google Gemini",

      keyExists:
        true,

      availableModels,
    });
  } catch (err: any) {
    return NextResponse.json({
      ok: false,

      error:
        err?.message ||
        "Failed to fetch models from Google",
    });
  }
}

/*
 * ==================================================
 * POST
 * ==================================================
 */

export async function POST(
  request: NextRequest
) {
  const started =
    Date.now();

  try {
    let body: AIRequest;

    try {
      body =
        (await request.json()) as AIRequest;
    } catch {
      return NextResponse.json(
        {
          ok: false,

          error:
            "Invalid or empty JSON body in request.",
        },
        {
          status: 400,
        }
      );
    }

    /*
     * ------------------------------------------------
     * REQUEST
     * ------------------------------------------------
     */

    const task =
      typeof body.task ===
      "string"
        ? body.task.trim()
        : "";

    const requestedPaths =
      Array.isArray(
        body.paths
      )
        ? body.paths.filter(
            item =>
              typeof item ===
              "string"
          )
        : [];

    const requestedChannel =
      typeof body.channel ===
      "string"
        ? body.channel.trim()
        : "";

    const includeRadar =
      body.includeRadar !==
      false;

    const profile:
      ContextProfile =
      body.profile ===
        "CONTENT" ||
      body.profile ===
        "RESEARCH" ||
      body.profile ===
        "ANALYTICS"
        ? body.profile
        : "GENERAL";

    if (!task) {
      return NextResponse.json(
        {
          ok: false,

          error:
            "Task is required.",
        },
        {
          status: 400,
        }
      );
    }

    /*
     * ------------------------------------------------
     * LIBRARIAN → RETRIEVER
     * ------------------------------------------------
     */

    const retrievalSeed =
      buildRetrievalSeed(
        task,
        profile,
        requestedPaths
      );

    const retrievalPackage =
      await buildRetrievalPackage(
        PROJECT_ROOT,
        retrievalSeed,
        {
          maxCharacters:
            RETRIEVAL_MAX_CHARACTERS,

          maxSources:
            RETRIEVAL_MAX_SOURCES,
        }
      ) as RetrievalPackage;

    const retrieved =
      await buildRetrievedContext(
        retrievalPackage,
        includeRadar
      );

    /*
     * ------------------------------------------------
     * OUTPUT CONTRACT
     * ------------------------------------------------
     */

    const outputContract =
      detectWriterOutputContract(
        task
      );

    /*
     * ------------------------------------------------
     * CONTENT STRATEGY
     * ------------------------------------------------
     */

    const strategyContext =
      await loadStrategyContext();

    /*
     * ------------------------------------------------
     * CONTENT PLANNER
     * ------------------------------------------------
     *
     * Important:
     *
     * requestedChannel is passed explicitly.
     *
     * If it exists, Planner MUST use it.
     * If empty, Planner chooses channel according
     * to the strategic documents.
     */

    const planner =
      await callAI(
        buildPlannerSystemPrompt(),

        buildPlannerUserPrompt({
          task,

          profile,

          context:
            retrieved.context,

          strategyContext,

          requestedChannel,
        }),

        6000,

        {
          responseMimeType:
            "application/json",

          responseSchema:
            CONTENT_PLAN_SCHEMA,
        }
      );

    const contentPlan =
      parseContentPlan(
        planner.content
      );

    /*
     * ------------------------------------------------
     * CHANNEL SAFETY CHECK
     * ------------------------------------------------
     *
     * If the request explicitly specified a channel,
     * Planner's answer must match it.
     *
     * This protects the architecture from an LLM
     * silently switching to another channel.
     */

    if (
      requestedChannel &&
      contentPlan.channel !==
        requestedChannel
    ) {
      console.warn(
        "PLANNER CHANNEL OVERRIDE:",
        {
          requestedChannel,
          plannerChannel:
            contentPlan.channel,
        }
      );

      contentPlan.channel =
        requestedChannel;

      contentPlan.constraints =
        [
          ...contentPlan.constraints,

          `Explicit channel requirement: ${requestedChannel}. Planner output was normalized to the requested channel.`,
        ];
    }

    const plannerBrief =
  formatContentPlanForWriter(
    contentPlan
  );

    /*
     * ------------------------------------------------
     * WRITER
     * ------------------------------------------------
     */

    const writerSystemPrompt =
      buildWriterSystemPrompt(
        outputContract
      );

    const systemPrompt =
      `${buildSystemPrompt(
        profile
      )}

==================================================
CONTENT PLANNER EXECUTION LAYER
==================================================

The Content Planner has already converted the user's request into a strategic execution brief.

The selected PRIMARY CHANNEL is authoritative.

The Writer MUST follow the PRIMARY CHANNEL specified in the Content Planner Brief.

Do not silently move the content to another channel.

The Writer must adapt tone, depth, structure, CTA and presentation to the selected channel.

Treat the retrieved project sources as the factual source of truth.

Do not invent information that is absent from the sources.

${plannerBrief}

==================================================
WRITER EXECUTION LAYER
==================================================

${writerSystemPrompt}
`;

    const userPrompt =
      buildWriterUserPrompt({
        task,

        profile,

        context:
          `${plannerBrief}

RETRIEVED PROJECT CONTEXT:

${retrieved.context}`,

        outputContract,
      });

    const ai =
      await callAI(
        systemPrompt,
        userPrompt,
        4000
      );

    /*
     * ------------------------------------------------
     * VALIDATOR
     * ------------------------------------------------
     */

    const validation =
      await validateWriterOutput({
        task,

        outputContract,

        content:
          ai.content,

        context:
          retrieved.context,

        projectRoot:
          PROJECT_ROOT,
      });

    /*
     * ------------------------------------------------
     * RESPONSE
     * ------------------------------------------------
     */

    return NextResponse.json({
      ok: true,

      result:
        ai.content,

      meta: {
        profile,

        requestedChannel:
          requestedChannel ||
          null,

        outputContract,

        contentPlan,

strategyDocuments:
  STRATEGY_FILES,

        plannerModel:
          planner.model,

        model:
          ai.model,

        provider:
          "Google Gemini",

        filesLoaded:
          retrieved.filesLoaded,

        sources:
          retrieved.sources,

        radarIncluded:
          includeRadar,

        contextCharacters:
          retrieved.contextCharacters,

        retrieval: {
          limits:
            retrievalPackage.limits,

          composition:
            retrievalPackage.composition,

          selected:
            retrievalPackage.selected.map(
              candidate => ({
                path:
                  candidate.item?.path ||
                  candidate.item?.title ||
                  "",

                role:
                  candidate.role ||
                  candidate.item?.sourceRole ||
                  candidate.item?.type ||
                  "source",

                relevance:
                  candidate.relevance ??
                  null,

                size:
                  candidate.size ??
                  null,

                reasons:
                  candidate.reasons ||
                  [],
              })
            ),
        },

        durationMs:
          Date.now() -
          started,

        plannerUsage:
          planner.usage,

        usage:
          ai.usage,

        writerFinishReason:
          ai.finishReason,

        validation: {
          status:
            validation.status,

          score:
            validation.score,

          summary:
            validation.summary,

          violations:
            validation.violations,

          rulesLoaded:
            validation.rulesLoaded,
        },
      },
    });
  } catch (error) {
    console.error(
      "AI GATEWAY ERROR:",
      error
    );

    return NextResponse.json(
      {
        ok: false,

        error:
          error instanceof Error
            ? error.message
            : "Unknown AI gateway error.",
      },
      {
        status: 500,
      }
    );
  }
}